Change Example & Set -Group Param to not be mandatory
chocolatey/ChocoCCM pull request #54
Opened 2021-08-12 02:56 UTC by ryanrichter94

Fixes #50 

Changed example to only use mandatory parameters. Also changed -Group parameter to no longer be mandatory as originally intended.

2021-08-12 17:13 UTC, pauby commented
There are a lot of commits in here not related to the PR. I think you're going to rebase your branch @ryanrichter94

2022-04-01 23:14 UTC, corbob requested changes
This change does **not** work at all. With the parameters set the way that they in the PR, PowerShell 5.1 is unable to bind the parameters. @ryanrichter94 and I did some work to get the binding working, and got it to a point where it executes, but comes back with a 400 error from CCM. PowerShell 7 doesn't have this issue. I'd hold off on doing more on this particular PR until we can determine supported PowerShell version and how to handle this in a way that works for all supported versions.

![image](https://user-images.githubusercontent.com/30301021/161353260-ca8bdb38-0ffc-4d72-9f0a-1dcd60aa62c1.png)

2023-07-06 20:27 UTC, vexx32 commented
@corbob I've had another look here and I believe I've got the parameter binding working (it still says "mandatory" but you can use either -Group or -Computer on their own, PS parameter binding does mandatory-by-set).

Looking at your JSON results there too, I'm pretty confident the solution here should work as well, as it avoids the weird json structure that was breaking in 5.1, from my local testing. The resulting json seems to be the same in 5.1 and pwsh 6+ now, so this _should_ be sorted.

2023-07-07 19:52 UTC, corbob approved these changes
LGTM!

2023-07-20 21:10 UTC, vexx32 commented on src/Public/Add-CCMGroupMember.ps1
> +            }
This construction still breaks, it looks like... the JSON conversion in WinPS strips off the array wrapper if there's only one element. Looks like the "proper" way to do this is just `Computers = $ComputerCollection` / `Groups = $GroupCollection`, it seems to work properly for empty arrays and all.

2023-07-21 23:05 UTC, corbob commented
For some level of completeness, how I tested this:
1. Checked out this branch on a CCM server
2. Imported `./src/ChocoCCM.psd1`
3. Ran `Add-ccmgroupmember -name mine -computer win2019`
4. Ran `Add-ccmgroupmember -name lkj -group mine`
5. Verified the groups in CCM web interface.

It all seemed to work for me.

2023-07-21 23:06 UTC, merged

2023-07-21 23:06 UTC, corbob commented
Thanks for getting this updated @ryanrichter94 and @vexx32 for helping get it over the line.